---
# tasks file for demoapp
- name: start mongodb
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-mongodb'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: demodb
        template:
          metadata:
            labels:
              app: demodb
          spec:
            containers:
            - name: demodb
              image: "docker.io/mongo"
              ports:
                - containerPort: 27017
- name: start mongodb Service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: 'demodb'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          app: demodb
        type: ClusterIP
        ports: 
        - port: 27017
          protocol: TCP               
- name: start demo app
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-demoapp'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: demoapp
        template:
          metadata:
            labels:
              app: demoapp
          spec:
            containers:
            - name: demoapp
              image: "docker.io/mayankb1712/startertutorial:hellomongo"
              ports:
                - containerPort: 8102
              env:
                - name: spring.data.mongodb.host
                  value: demodb
- name: start demo app Service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: 'demoapp'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          app: demoapp
        type: NodePort
        ports: 
        - port: 8102
          nodePort: 30001
